services:
  - type: worker
    name: telegram-qwen-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DASHSCOPE_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
